### ISSUE TITLE
New ISO 20022 camt.054 creditor order notification version (04 to 08)

### ISSUE THREAD

**Issue by mauricelehmann** [viafintech/camt_parser#70]
Hey !

We are currently having issue with the new ISO 20022 camt.054 version (from 04 to 08 in our bank).
The changes are listed below : 

<img width="787" alt="Capture d’écran 2024-09-24 à 10 34 16" src="https://github.com/user-attachments/assets/46e9a279-dd43-464c-ae9d-5a2a59831ff4">

As a quickfix, we just added this line in an initializer : 
 `CamtParser::Xml.register('urn:iso:std:iso:20022:tech:xsd:camt.054.001.08', :camt054)`

My question is : does any contributor already working on a PR for thoses changes ? If not, i'd be happy to try to make one, but i'm not very familiar with this project, so i don't even know if it's doable or complicated.

More info here :
https://www.postfinance.ch/en/business/knowledge/news/replace-the-iso-20022-camt054-creditor-order-notification-version-2-2009.html

Thanks in advance ! 

Maurice

**Comment by tobischo** [comment]
Hi @mauricelehmann,
no one is working on this yet. This sort of thing is added as needed.

Your quickfix is exactly how this gem is intended to be used in the absence of "official" support for a schema version.
The specific fields are also rather made accessible as needed instead of everything and it is up to the user to select the fields. In the end it is just a convenient way to get from XML to an object.

So if there is any specific fields that you need to access which are available in the new version, we can add them.
Otherwise adding the `register` line might be all that is needed.

I would generally suggest to switch to https://github.com/viafintech/sepa_file_parser which has a slightly broader application than just CAMT files, but I would be open to making this change in both places.

Long term I intended to stop supporting camt_parser in favor of sepa_file_parser.

**Comment by mauricelehmann** [comment]
Alright, thank for your quick response ! I'll check with my team about those changes. I don't think we need those new fields, so for now we can keep the register. And we also will check for moving to the sepa_file_parser. 

Thank again ! 
Cheers !
